FROM nginx

ENV NGINX_VERSION nginx-1.25.2

RUN apt update && apt upgrade -y
RUN set -x \
    && apt install vim git build-essential libpcre3-dev libssl-dev zlib1g-dev libgd-dev -y

WORKDIR /tmp
COPY $NGINX_VERSION.tar.gz .
RUN tar -xvzf $NGINX_VERSION.tar.gz

# https://github.com/LoicMahieu/alpine-nginx/blob/master/Dockerfile
# https://github.com/docker/awesome-compose/tree/master
WORKDIR /tmp/$NGINX_VERSION
RUN ./configure \
        --prefix=/etc/nginx \
        --sbin-path=/usr/sbin/nginx \
        --modules-path=/usr/lib/nginx/modules \
        --conf-path=/etc/nginx/nginx.conf \
        --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log \
        --pid-path=/var/run/nginx.pid \
        --lock-path=/var/run/nginx.lock \
        --user=nginx --group=nginx \
        --http-client-body-temp-path=/var/cache/nginx/client_temp \
        --http-proxy-temp-path=/var/cache/nginx/proxy_temp \
        --http-fastcgi-temp-path=/var/cache/nginx/fastcgi_temp \
        --http-uwsgi-temp-path=/var/cache/nginx/uwsgi_temp \
        --http-scgi-temp-path=/var/cache/nginx/scgi_temp \
        --with-compat \
        --with-file-aio \
        --with-threads \
        --with-http_addition_module \
        --with-http_auth_request_module \
        --with-http_gunzip_module \
        --with-http_gzip_static_module \
        --with-http_mp4_module \
        --with-http_realip_module \
        --with-http_secure_link_module \
        --with-http_slice_module \
        --with-http_ssl_module \
        --with-http_stub_status_module \
        --with-http_sub_module \
        --with-http_v2_module --with-http_v3_module \
        --with-pcre \
        --with-http_image_filter_module=dynamic \
        --without-http_autoindex_module \
        --without-http_fastcgi_module \
        --with-stream \
        --with-stream_realip_module \
        --with-stream_ssl_module \
        --with-stream_ssl_preread_module \
#        --with-http_dav_module \
#        --with-http_flv_module \
#        --with-http_random_index_module \
#        --with-mail_ssl_module \
        --with-cc-opt='-g -O2 -ffile-prefix-map=/data/builder/debuild/nginx-1.25.2/debian/debuild-base/nginx-1.25.2=. -fstack-protector-strong -Wformat -Werror=format-security -Wp,-D_FORTIFY_SOURCE=2 -fPIC' \
        --with-ld-opt='-Wl,-z,relro -Wl,-z,now -Wl,--as-needed -pie' \
    && make \
    && make install

WORKDIR /root
COPY ./bashrc .

# WORKDIR /etc/nginx
# COPY nginx.conf .
# COPY servers servers

# WORKDIR /app
# COPY ./default default

# WORKDIR /root
# COPY bashrc/. .

EXPOSE 80 443
CMD ["nginx", "-g", "daemon off;"]