version: '3.8'
services:
  proxy:
    restart: always
    build: .
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./sites-available:/etc/nginx/sites-available
      - ./default:/app/default