version: '3.9'
services:
  webserver:
    container_name: webserver
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '8080:80'
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./servers:/etc/nginx/servers
      - ./default:/app/default